apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knix-hostpath
  namespace: default
spec:
  selector:
    matchLabels:
      app: knix-hostpath
  template:
    metadata:
      labels:
        app: knix-hostpath
    spec:
      initContainers:
      - name: init
        command:
        - fish
        - -c
        - "echo asdf && sleep 5 && cp --verbose --archive --update=none /nix/* /nix2/"
        image: rg.nl-ams.scw.cloud/lillecarl/knix:latest
        volumeMounts:
        - mountPath: /nix2
          name: knix
        imagePullPolicy: Always
      containers:
      - name: sleeper
        image: rg.nl-ams.scw.cloud/lillecarl/knix:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: knix
          mountPath: /nix
        - name: knixdev
          mountPath: /knix
        env:
        - name: KNIX_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        imagePullPolicy: Always
      volumes:
      - name: knix
        hostPath:
          path: /var/lib/knix/nix
          type: DirectoryOrCreate
      - name: knixdev
        hostPath:
          path: /home/lillecarl/Code/knix
          type: Directory
