--- # ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cknix
  namespace: default
--- # Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cknix
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
--- # Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cknix-binding
subjects:
- kind: ServiceAccount
  name: cknix
  namespace: default
roleRef:
  kind: ClusterRole
  name: cknix
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cknix-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: cknix-deployment
  template:
    metadata:
      labels:
        app: cknix-deployment
    spec:
      serviceAccountName: cknix
      containers:
      - name: sleeper
        image: nixpkgs/nix-flakes
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: cknixdev
          mountPath: /cknix
      volumes:
      - name: cknixdev
        hostPath:
          path: /home/lillecarl/Code/cknix
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: cknix-deployment
  namespace: default
spec:
  selector:
    app: cknix-deployment
  ports:
    - name: zmq-pub
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
